services:  
  challenge.process.aiq.webapi:
    image: challenge.process.aiq.webapi
    ports:
      - "8082:8080"
    build:
      context: .
      dockerfile: src/Challenge.Process.Aiq.WebApi/Dockerfile
    
  db:
    container_name: postgresql
    image: postgres:17.4
    restart: always      
    shm_size: 128mb    
    tty: true    
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: adm12345
        POSTGRES_USER: user
        POSTGRES_DB: challenge

networks:
  dbnet:
    driver: bridge